name: "Run AI Sec Demo"

on:
  push:
    branches:
      - main
    paths:
      - "s3_module/**"
  pull_request:
    branches:
      - html_report_support
    paths:
      - "s3_module/**"

jobs:
  run-ai-sec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AI Sec Linter
        uses: darrenrabbs/ai-sec-action@v3
        with:
          infra_dir: "${{ github.workspace }}/s3_module"
          config_path: "${{ github.workspace }}/config/config.yaml"
          openai_api_token: ${{ secrets.OPENAI_API_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
